---
title: "matrizPagos"
author: "LauraGabriel"
date: "2023-08-28"
---
```{r}
# Definir la función para calcular la ganancia
calcular_ganancia <- function(demanda, pedido) {
  precio_venta <- 120
  precio_compra_100 <- 100
  precio_compra_200 <- 90
  precio_compra_300 <- 85
  precio_remate <- 60

  if (pedido <= 100) {
    precio_compra <- precio_compra_100
  } else if (pedido <= 200) {
    precio_compra <- precio_compra_200
  } else {
    precio_compra <- precio_compra_300
  }
  ganancia <- precio_venta - precio_compra
  
   if (demanda == pedido) {
      return (demanda * ganancia)      
  } else if (demanda < pedido) {
      return (demanda * ganancia + (pedido -demanda) * (precio_remate - precio_compra))
  } else {
    return  ((pedido * ganancia) - (5*(demanda - pedido)) )
  }

}

# Crear una tabla con los valores de pedido y demanda
pedidos <- c(100, 200, 300)
demandas <- c(100, 150, 200)

tabla <- matrix(NA, nrow = length(demandas), ncol = length(pedidos))
#establecer los valores de las filas y comlumnas
rownames(tabla) <- demandas
colnames(tabla) <- pedidos
#llenar la matriz deacuerdo a las demandas y pedidos
for (i in 1:length(demandas)) {
  for (j in 1:length(pedidos)) {
    tabla[j, i] <- calcular_ganancia(demandas[j], pedidos[i])
  }
}

tabla